from __future__ import annotations

from ._legacy import (
    _ambiguous_signature,
    _analyze_chart_visual_pattern,
    _analyze_structured_layout,
    _build_clean_visible_text,
    _collect_active_segments,
    _collect_chart_visible_text,
    _collect_layout_visible_text,
    _count_keyword_hits,
    _dedupe_texts,
    _detect_direction_from_series,
    _detect_visual_scene,
    _extract_chart_text_structure,
    _format_chart_text_details,
    _format_layout_details,
    _looks_like_url_or_query,
    _match_common_ui_text,
    _merge_ocr_lines,
    _normalize_ocr_lines,
    _normalize_short_text_list,
    _ocr_line_text_quality,
    _repair_short_ui_text,
    _repair_url_like_text,
    _stabilize_layout_text,
    _structured_summary_labels,
)

__all__ = [
    "_ambiguous_signature",
    "_analyze_chart_visual_pattern",
    "_analyze_structured_layout",
    "_build_clean_visible_text",
    "_collect_active_segments",
    "_collect_chart_visible_text",
    "_collect_layout_visible_text",
    "_count_keyword_hits",
    "_dedupe_texts",
    "_detect_direction_from_series",
    "_detect_visual_scene",
    "_extract_chart_text_structure",
    "_format_chart_text_details",
    "_format_layout_details",
    "_looks_like_url_or_query",
    "_match_common_ui_text",
    "_merge_ocr_lines",
    "_normalize_ocr_lines",
    "_normalize_short_text_list",
    "_ocr_line_text_quality",
    "_repair_short_ui_text",
    "_repair_url_like_text",
    "_stabilize_layout_text",
    "_structured_summary_labels",
]
