from __future__ import annotations

from ._legacy import (
    _build_ocr_retry_image,
    _empty_ocr_result,
    _env_flag,
    _env_int,
    _extract_numeric_markers,
    _extract_readable_labels,
    _normalize_text,
    _ocr_backend_preference,
    _ocr_line_text_quality,
    _ocr_signal_score,
    _ocr_timeout_seconds,
    _parse_tesseract_tsv,
    _run_local_ocr,
    _run_local_ocr_with_backend,
    _run_tesseract_ocr,
    _run_windows_ocr,
    _should_retry_ocr,
    _tesseract_lang,
    _tesseract_psm,
    get_local_image_capabilities,
    has_local_image_support,
    has_tesseract_ocr_support,
    has_windows_ocr_support,
)

__all__ = [
    "_build_ocr_retry_image",
    "_empty_ocr_result",
    "_env_flag",
    "_env_int",
    "_extract_numeric_markers",
    "_extract_readable_labels",
    "_normalize_text",
    "_ocr_backend_preference",
    "_ocr_line_text_quality",
    "_ocr_signal_score",
    "_ocr_timeout_seconds",
    "_parse_tesseract_tsv",
    "_run_local_ocr",
    "_run_local_ocr_with_backend",
    "_run_tesseract_ocr",
    "_run_windows_ocr",
    "_should_retry_ocr",
    "_tesseract_lang",
    "_tesseract_psm",
    "get_local_image_capabilities",
    "has_local_image_support",
    "has_tesseract_ocr_support",
    "has_windows_ocr_support",
]
